### PR TITLE
Support standalone filament forms

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
ping

**Review by oyepez003 — APPROVED** [review]

**Comment by oyepez003** [comment]
Thanks for your PR @mohamedsabil83

**Comment by oyepez003** [comment]
@mohamedsabil83 This PR was reverted because this plugin uses the Filament facade to load the field styles...

Sorry :(

**Comment by mohamedsabil83** [comment]
Nevermind. what if we add a check as I did [here](https://github.com/mohamedsabil83/filament-forms-tinyeditor/blob/34722314c557891156e31ac42c210714be175950/src/FilamentFormsTinyeditorServiceProvider.php#L25)?

**Pull request merged**
